on:
  push:
    branches:
      - "ready"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          cd service_adify
          mvn install
          cd ..
          cd service_gateway
          mvn install