on:
  push:
    branches:
      - "ready/**"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          cd service_adify
          mvn install
          cd ..
          cd service_gateway
          mvn install
  
  tests:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Testing
        run: |
          cd service_adify
          mvn test -DskipTests=false -Dgroups=fast
          cd ..

  merge:
    runs-on: ubuntu-latest
    needs: [build, tests]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git checkout ${GITHUB_REF#refs/heads/}
          git rebase origin/master
          git branch master
          git push origin master:master
          git push origin :${GITHUB_REF#refs/heads/}  