on:
  push:
    branches:
      - "ready/**"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile
        run: mvn install
    
  systemtest:
    runs-on: ubuntu-latest
    working-directory: systemtest
    run: |
      

    
  pushtomaster:
    runs-on: ubuntu-latest
    needs: [build, systemtest]
    
    
    
  
